import "package:flutter/material.dart";

const IconSize = 35.0;
const SmallTextSize = 12.0;
const LargeTextSize = 22.0;
const MediumTextSize = 16.0;
const HeadLineTextSize = 20.0;
const DefaultPaddingHorz = 12.0;
const LocationTileHeight = 100.0;
const Color TextColorDark = Colors.black;
const Color TextColorLight = Colors.white;
const Color TextColorAccent = Colors.black;
const RefreshIndicatorDisplacement = 60.0;
const String FontNameDefault = 'OpenSans';
const EdgeInsets SliverGridPadding = EdgeInsets.all(20.0);
const Color TextColorFaint = Color.fromRGBO(125, 125, 125, 1.0);

// Material main theme color
// Generated by http://mcg.mbitson.com/
const int _PrimaryValue = 0xFF4caf50;
const MaterialColor CustomGreenPalette = MaterialColor(
  _PrimaryValue,
  <int, Color>{
    50: Color(0xffe8f5e9),
    100: Color(0xffc8e6c9),
    200: Color(0xffa5d6a7),
    300: Color(0xff81c784),
    400: Color(0xff66bb6a),
    500: Color(0xff4caf50),
    600: Color(0xff43a047),
    700: Color(0xff388e3c),
    800: Color(0xff2e7d32),
    900: Color(0xff1b5e20),
  },
);

const AppBarTextStyle = TextStyle(
  fontFamily: FontNameDefault,
  fontWeight: FontWeight.w400,
  fontSize: HeadLineTextSize,
  color: Colors.white,
);

const TitleTextStyle = TextStyle(
  fontFamily: FontNameDefault,
  fontWeight: FontWeight.w300,
  fontSize: LargeTextSize,
  color: TextColorDark,
);

const SubTitleTextStyle = TextStyle(
  fontFamily: FontNameDefault,
  fontWeight: FontWeight.w300,
  fontSize: MediumTextSize,
  color: TextColorAccent,
);

const CaptionTextStyle = TextStyle(
  fontFamily: FontNameDefault,
  fontWeight: FontWeight.w300,
  fontSize: SmallTextSize,
  color: TextColorDark,
);

const Body1TextStyle = TextStyle(
  fontFamily: FontNameDefault,
  fontWeight: FontWeight.w300,
  fontSize: MediumTextSize,
  color: Colors.white,
);